### DISCUSSION TITLE
Multiple download folder

### DISCUSSION THREAD

**Discussion by darktweek** [antlafarge/jdownloader#17] [Q&A] [answered]
Hi !

Can we use multiple file folder ?
I have 2 drive for my movies and series.

Thanks for the answers.

**Comment by antlafarge** [comment, marked as answer]
Hello, yes you should configure your volumes like that:
```
services:
  jdownloader:
    image: antlafarge/jdownloader:latest
    container_name: jdownloader
    restart: on-failure:10
    user: 1000:1000
    volumes:
      - "/mnt/hdd/Downloads:/jdownloader/downloads"
      - "/mnt/hdd/Movies:/jdownloader/downloads/movies"
      - "/mnt/hdd/Series:/jdownloader/downloads/series"
      - "/mnt/hdd/Apps/JDownloader/cfg:/jdownloader/cfg"
    environment:
      - "JD_EMAIL=my@email.fr"
      - "JD_PASSWORD=MyGreatPassword"
    ports:
      - "3129:3129" # optional
```

I supposed your regular downloads directory is here : `/mnt/hdd/Downloads`
I supposed your movies directory is here : `/mnt/hdd/Movies`.
I supposed your series directory is here : `/mnt/hdd/Series`.
(Don't forget to create and give correct permissions to these directories)

And don't forget to change the download directory in the JDownloader package :
![image](https://user-images.githubusercontent.com/2077556/140388354-2ed7052b-cc07-4a93-aeea-788b437e40a8.png)

By one of these : `/jdownloader/downloads/series` or `/jdownloader/downloads/movies` (corresponding on the right part of the added volumes settings above).
![image](https://user-images.githubusercontent.com/2077556/140388481-8f127029-9e84-4051-9a4b-14e8a06f6319.png)
