### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by Futos** [antlafarge/jdownloader#14]
Hey Guys,
Since the latest update, I have the problem that I get constantly the following Error in my Log,
what could I do in order to get it running again? thanks for your support :)

`/bin/bash: ./docker-entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory`

Docker-compose:

```
services:
  jdownloader:
    image: antlafarge/jdownloader:latest
    container_name: jdownloader # optional
    restart: always # optional
    user: 1001:1001 # optional
    volumes:
      - "/mnt/storage/media/downloads:/jdownloader/downloads"
      - "/opt/appdata/JDownloader/Config:/jdownloader/cfg" # optional
      - "/opt/appdata/JDownloader/Logs:/jdownloader/logs" # optional
    environment:
      - "JD_EMAIL=myEmailAdress"
      - "JD_PASSWORD=myPassword"
```

cheers
Futos
