### ISSUE TITLE
Can't download JDownloader.jar

### ISSUE THREAD

**Issue by daniauri** [antlafarge/jdownloader#18]
Hi, I'm using this docker for a while now and id worked flawlessly for some while. Big thanks for that.

Last months update (removed the old and docker-compose downloaded the image on start) of the docker image broke something. I'm getting that the JDownloader.jar can't be downloaded. As far as I can see the jar is pulled in docker-entrypoint.sh but curl throws error code 6, which means as much as URL not found/resolved.

My docker log output is this: 
```
jdownloader  | ./docker-entrypoint.sh: line 27: dpkg: command not found                                                                
jdownloader  | 2021-11-09T21:53:30+00:00| ________________________________________ CONTAINER STARTED __________________________________
_______                                                                                                                                
jdownloader  | 2021-11-09T21:53:30+00:00| OS is Alpine Linux v3.14                                                                     
jdownloader  | 2021-11-09T21:53:30+00:00| Java version is                                                                              
jdownloader  | 2021-11-09T21:53:30+00:00| Delete any existing JDownloader installation files                                           
jdownloader  | 2021-11-09T21:53:30+00:00| Download JDownloader.jar                                                                     
jdownloader  | 2021-11-09T21:53:35+00:00| FATAL ERROR JDownloader.jar download failed: curl exited with code '6'                       
jdownloader  | 2021-11-09T21:53:35+00:00| Get more informations here : https://github.com/antlafarge/jdownloader#troubleshooting       
jdownloader  | 2021-11-09T21:53:35+00:00| _________________________________________ CONTAINER EXITED __________________________________
_______                                                                                                                                
```
I tried running as unpriviliged user (was my default before it broke) and without the user option with docker-compose.
Also tried alpine and ubuntu tag - same result.

```
  jdownloader:
    image: antlafarge/jdownloader:alpine
    container_name: jdownloader # optional
    restart: on-failure:3 # optional
      #user: 963:963 # optional
    volumes:
      - "/media/downloads:/jdownloader/downloads"
      - "/media/downloader/.config:/jdownloader/cfg" # optional
      - "/media/downloader:/jdownloader/logs" # optional
    environment:
      - "JD_EMAIL=mail@mail.mail"
      - "JD_PASSWORD=*************"
      - "JD_DEVICENAME=JD-DOCKER" # optional
    ports:
      - "3129:3129" # optional
```
