### ISSUE TITLE
Sending links with MyJDownloader is not reliable

### ISSUE THREAD

**Issue by pngmn** [antlafarge/jdownloader#20]
Sending links with the MyJDownloader extension for Firefox does not work all the time, I have to send the links multiple times.
Here is my service in the compose file:
```
  jdownloader:
    container_name: jdownloader
    image: antlafarge/jdownloader
    restart: unless-stopped
    network_mode: service:openvpn
    user: "${PUID}:${PGID}"
    volumes:
      - ${DOCKERDIR}/jdownloader/config:/jdownloader/cfg:rw
      - ${DOCKERDIR}/jdownloader/logs:/jdownloader/logs:rw
      - ${ZFS_SHARE2}:/jdownloader/downloads/share:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JD_EMAIL=${JD_MAIL}
      - JD_PASSWORD=${JD_PASS}
      - JD_DEVICENAME=nuc
```

Switching to this image resolves the problem. Both container use the same config directory. (I don't run them at the same time).
```
  jdownloader:
    container_name: jdownloader
    image: plusminus/jdownloader2-headless
    restart: unless-stopped
    network_mode: service:openvpn
    volumes:
      - ${DOCKERDIR}/jdownloader/config:/opt/JDownloader/cfg:rw
      - ${DOCKERDIR}/jdownloader/logs:/opt/JDownloader/logs:rw
      - ${ZFS_SHARE2}:/jdownloader/downloads/share:rw
    environment:
      - EMAIL=${JD_MAIL}
      - PASSWORD=${JD_PASS}
      - UID=${PGID}
      - GID=${PUID}
```

Is there anything in the logs I should look for?

For completeness the openvpn container where port 3129 is exposed
```
  openvpn:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn
    restart: always
    ports:
      - 3129:3129
    environment:
      - SUBNETS=${OPENVPN_NETWORKS}
      - KILL_SWITCH=on
      - VPN_LOG_LEVEL=3
    volumes:
      - ${DOCKERDIR}/openvpn:/data/vpn:rw
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
```

**Comment by pngmn** [comment]
I have set up direct connection for my local subnet, so it shouldn't send the links through my vpn. Also after a container restart I don't have these problems for some time. My theory is that the automatic updates somehow cause my problem. For testing purposes I switched to a bridge network instead of the vpn.

**Comment by antlafarge** [comment]
I don't see any reason why the automatic update would cause this problem. It checks every hour if the container has to be updated, and proceed to the update if it is idle (linkgrabber and download), else it will be updated later. It should not interfere with the features.
Do you have the same problems without using the VPN with my image? With another image?

**Comment by pngmn** [comment]
It's hard to test, because I can't reproduce it reliably. It usually fails if jdownloader is idle for a long time.

I just had it happen without the vpn. I sent the link and nothing was showing up on the webinterface. Sending the link a second time worked though. With the image `plusminus/jdownloader2-headless` I don't have these problems with or without the vpn.

This is my current compose:
````yaml
  jdownloader:
    container_name: jdownloader
    image: antlafarge/jdownloader
    restart: unless-stopped
    # network_mode: service:openvpn
    ports:
      - 3129:3129
    user: "${PUID}:${PGID}"
    volumes:
      - ${DOCKERDIR}/jdownloader/config:/jdownloader/cfg:rw
      - ${DOCKERDIR}/jdownloader/logs:/jdownloader/logs:rw
      - ${ZFS_SHARE2}:/jdownloader/downloads/share:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JD_EMAIL=${JD_MAIL}
      - JD_PASSWORD=${JD_PASS}
      - JD_DEVICENAME=nuc
```
