### ISSUE TITLE
Container could not initialize on a read-only file system

### ISSUE THREAD

**Issue by VxDlH** [antlafarge/jdownloader#45]
First, thank you for your work.

A read-only file system produced these errors:
```
2024-12-01T23:10:11+00:00| Container started
2024-12-01T23:10:11+00:00|   OS = "Alpine Linux v3.20"
2024-12-01T23:10:11+00:00|   USER = "11000:11000"
2024-12-01T23:10:11+00:00|   JAVA version = "openjdk21-jre-headless-21.0.5_p11-r0"
2024-12-01T23:10:11+00:00|   WARNING "JD_EMAIL" not found
2024-12-01T23:10:11+00:00|   WARNING "JD_PASSWORD" not found
2024-12-01T23:10:11+00:00|   Check "JDownloader.jar"
2024-12-01T23:10:11+00:00|     Delete any existing JDownloader installation files
rm: can't remove './tmp': Read-only file system
rm: can't remove './update': Read-only file system
2024-12-01T23:10:11+00:00|     Download "https://installer.jdownloader.org/JDownloader.jar"
2024-12-01T23:10:11+00:00|     ERROR : curl exited with code "23"
2024-12-01T23:10:11+00:00|   Setup JDownloader
2024-12-01T23:10:11+00:00|     Create directory "./update/versioninfo/JD/"
2024-12-01T23:10:11+00:00|     Install "./update/versioninfo/JD/extensions.requestedinstalls.json"
2024-12-01T23:10:11+00:00|     Set JDownloader email
2024-12-01T23:10:11+00:00|     Set JDownloader password
2024-12-01T23:10:11+00:00|     Set JDownloader devicename
2024-12-01T23:10:11+00:00|   Start JDownloader
2024-12-01T23:10:11+00:00|     JDownloader started [PID=81]
2024-12-01T23:10:11+00:00|     JDownloader stopped
2024-12-01T23:10:11+00:00| Container stopped
```

This warning seems odd; my environment variables appear to be correctly configured.
```
 WARNING "JD_EMAIL" not found
 WARNING "JD_PASSWORD" not found
```
![image](https://github.com/user-attachments/assets/d690309c-78a9-4128-8cd0-44422ca7af16)

but this point is not a showstopper

https://github.com/antlafarge/jdownloader/blob/1f8738c84e2dbfacdbd9ad1ec9a33dce34cdca4f/src/docker-entrypoint.sh#L45

`rm: can't remove` error can be fixed by adjusting the line:
https://github.com/antlafarge/jdownloader/blob/1f8738c84e2dbfacdbd9ad1ec9a33dce34cdca4f/src/docker-entrypoint.sh#L74
by this one : 
```
rm -f -r $JDownloaderJarFile Core.jar ./tmp/* ./update/*
```

This issue is optimally resolved using the ./tmp folder 
```
Download "https://installer.jdownloader.org/JDownloader.jar"
ERROR : curl exited with code "23"
```
https://github.com/antlafarge/jdownloader/blob/1f8738c84e2dbfacdbd9ad1ec9a33dce34cdca4f/src/docker-entrypoint.sh#L79
by this one : 
```
downloadFile "https://$JDownloaderJarUrl" "./tmp/$JDownloaderJarFile"
```

- Generally, it is recommended to use the system's default `/tmp` directory for all temporary files.
- If it needs to be emptied, it is preferable to delete `/tmp/*`.
- On a read-only system, it is easier to create a mount point for `/tmp`.

**Comment by antlafarge** [comment]
Hello, I don't understand why you use a read only file system ?
The container needs to create / delete files to work (jDownloader files and downloaded files)
Can you explain what are you trying to do?
Thank you

**Comment by antlafarge** [comment]
You have to know that `./tmp` and `./update` folders are created by jDownloader application. So I have no control on this.
And jDownloader.jar is not a temporary file, I delete the file (and linked subdirectory tmp and update) only if the file is corrupted and then re-download it.

**Comment by VxDlH** [comment]
The directories containing data (configuration directory and download directory) aren’t read-only, but the rest of the system is. This is the best practice when running dockers that have internet access.

**Comment by VxDlH** [comment]
> You have to know that `./tmp` and `./update` folders are created by jDownloader application. So I have no control on this. And jDownloader.jar is not a temporary file, I delete the file (and linked subdirectory tmp and update) only if the file is corrupted and then re-download it.

That's not a problem.  What I suggest is, instead of deleting the directory itself, it's preferable to delete its contents.

**Comment by antlafarge** [comment]
Okay for the use of /tmp directory by jDownloader app, I recommand to discuss of that in the official jDownloader forum.

For the warnings, can you share the docker compose or docker run command to reproduce it ?

And for the replacement of `rm -f -r $JDownloaderJarFile Core.jar ./tmp ./update ` by `rm -f -r $JDownloaderJarFile Core.jar ./tmp/* ./update/*`, I'm not against that if there is an issue.
But before changing anything, I need to understand why the tmp and update directory content can be deleted, but not the directories themselves ?

**Comment by VxDlH** [comment]
> Okay, for the use of /tmp directory by jDownloader app, I recommend discussing that in the official jDownloader forum.

Okay, no problem with that.


> For the warnings, can you share the docker compose or docker run command to reproduce it ?
I'm using your image on a Kubernetes cluster.

Here is my simplified file.

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jdownloader
  namespace: jdownloader
  labels:
    app: jdownloader
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jdownloader
  template:
    metadata:
      labels:
        app: jdownloader
    spec: 
      securityContext:
        runAsUser: 11000
        runAsGroup: 11000
        fsGroup: 11000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: antlafarge/jdownloader:alpine-openjdk21
          securityContext:
           allowPrivilegeEscalation: false
           readOnlyRootFilesystem: true
           runAsNonRoot: true
           seccompProfile:
             type: RuntimeDefault
           capabilities:
             drop:
             - "ALL"
          name: jdownloader
          ports:
            - containerPort: 3129
              name: myjd-access
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "jdownloader-configmap"
            - secretRef:
                name: "jdownloader-myjd"
          volumeMounts:
            - mountPath: /jdownloader/cfg/
              name: config
            - mountPath: /jdownloader/update/
              name: update
            - mountPath: /jdownloader/logs/
              name: logs
            - mountPath: /jdownloader/tmp
              name: tmp
            - mountPath: /jdownloader/downloads/
              name: downloads
      volumes:
       ...

```

- The /jdownloader directory is read-only.
- The /jdownloader/cfg/, /jdownloader/update/, /jdownloader/logs/, /jdownloader/tmp, and /jdownloader/downloads/ directories are read-write.

It is not possible to delete the directories /jdownloader/cfg/, /jdownloader/update/, /jdownloader/logs/, /jdownloader/tmp, and /jdownloader/downloads/. However, their contents can be deleted.
