### ISSUE TITLE
[Raspberry PI 4B / Raspberry OS Lite arm64 / Alpine image] OK

### ISSUE THREAD

**Issue by antlafarge** [antlafarge/jdownloader#8]
The image is working well.

**Comment by JanChodorowski** [comment]
Hi! I'm using this docker-compose.yml

``` 
  jdownloader:
    image: antlafarge/jdownloader:alpine
    container_name: jdownloader
    restart: always
    user: 1001:100
    volumes:
        - ./data/jdownloader:/opt/JDownloader/cfg
        - ~/Downloads:/opt/JDownloader/Downloads
    environment:
       - UID=1000
       - GUD=1000
       - JD_DEVICENAME=JD-DOCKER
    ports:
        - 3129:3129
```

and get the following errors

```
jdownloader     | 2021-06-22T17:05:22+0000| Create group 'jdgroup' (GID '1000')
jdownloader     | addgroup: permission denied (are you root?)
jdownloader     | functions.sh: line 83: [: ==: unary operator expected
jdownloader     | 2021-06-22T17:05:22+0000| FATAL ERROR groupadd exited with code '1'
```

How do I pass `--privileged` flag inside if the docker-compose.yml? Thanks and cheers
